min_particles: 100
max_particles: 1000
kld_err: 0.01
update_min_d: 0.1
update_min_a: 0.31415
#recovery_alpha_slow: 0.001
#recovery_alpha_fast: 0.1
initial_cov_xx: 4.00
initial_cov_yy: 4.00
initial_cov_aa: 9.8696
laser_min_range: -1.0
laser_max_range: -1.0
laser_max_beams: 128
laser_z_hit: 0.80
laser_z_short: 0.50
laser_z_max: 0.10
laser_z_rand: 0.10
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 3.0